---
abstract: 'sends log messages to a FirePHP console'
author:
  - 'Sebastian Willert, C<willert@cpan.org>'
build_requires:
  Test::Perl::Critic: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FirePHP-Dispatcher
no_index:
  directory:
    - inc
    - t
    - examples
recommends:
  Log::Log4perl: 0
requires:
  Class::Accessor::Fast: 0
  JSON::Any: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02_01
